apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: imamu-helper-pdb
  namespace: imamu
  labels:
    app.kubernetes.io/name: imamu-helper
    app.kubernetes.io/part-of: imamu-helper
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: imamu-helper
      app.kubernetes.io/component: web
