apiVersion: v1
kind: Secret
metadata:
  name: imamu-secret
  namespace: imamu
  labels:
    app.kubernetes.io/name: imamu-helper
    app.kubernetes.io/part-of: imamu-helper
type: Opaque
stringData:
  # CHANGE THESE VALUES BEFORE DEPLOYING TO PRODUCTION
  JWT_SECRET: "change-this-to-a-very-long-and-secure-random-secret-key-32chars"
  SQL_PASSWORD: "imamu_production_password"
  DATABASE_URL: "postgresql://imamu:imamu_production_password@imamu-postgres:5432/imamu?sslmode=disable"
  IMAMU_BACKUP_PASSWORD: "backup_production_password"

  # Garage / S3 Credentials
  S3_ACCESS_KEY_ID: "GKbb93a64d9b59553812b16ab7"
  S3_SECRET_ACCESS_KEY: "7019369bc02559db1603063931261ccb4fab61b2cc4ac32c239a35295cb57705"
